void main() {
  Map<String, dynamic> country = {
    'gujrat': {
      'surat': {
        'amiras': {
          'name': 'amiras',
          'mo': 123456,
          'email': 'amiras@gmail.com',
          'rating': 4,
        },
        'surbhi': {
          'name': 'surbhi',
          'mo': 123457,
          'email': 'surbhi@gmail.com',
          'rating': 3.5,
        },
        'octant': {
          'name': 'octant',
          'mo': 123458,
          'email': 'octant@gmail.com',
          'rating': 3.5,
        },
        'ocean': {
          'name': 'ocean',
          'mo': 123459,
          'email': 'ocean@gmail.com',
          'rating': 5,
        },
        'avadh': {
          'name': 'avadh',
          'mo': 123451,
          'email': 'avadh@gmail.com',
          'rating': 4,
        },
      },
      'ahemdabad': {
        'bayleaf': {
          'name': 'bayleaf',
          'mo': 123452,
          'email': 'bayleaf@gmail.com',
          'rating': 5,
        },
        'Tinello': {
          'name': 'Tinello',
          'mo': 123453,
          'email': 'tinello@gmail.com',
          'rating': 4.5,
        },
        'Rajwadu': {
          'name': 'Rajwadu',
          'mo': 123454,
          'email': 'rajwadu@gmail.com',
          'rating': 3.5,
        },
        'Sasuji': {
          'name': 'sasuji',
          'mo': 123466,
          'email': 'sasuji@gmail.com',
          'rating': 3,
        },
        'TORITOS': {
          'name': 'TORITOS',
          'mo': 123476,
          'email': 'toritos@gmail.com',
          'rating': 4,
        },
      },
      'rajkot': {
        'SARAZA': {
          'name': 'SARAZA ',
          'mo': 123486,
          'email': 'saraza@gmail.com',
          'rating': 4,
        },
        'Madhav': {
          'name': 'Madhav',
          'mo': 123496,
          'email': 'madhav@gmail.com',
          'rating': 3.5,
        },
        'Rangoli': {
          'name': 'Rangoli',
          'mo': 123406,
          'email': 'Rangoli@gmail.com',
          'rating': 4.5,
        },
        'Sankalp': {
          'name': 'Sankalp',
          'mo': 123556,
          'email': 'sankalp@gmail.com',
          'rating': 5,
        },
        'tomatos': {
          'name': 'tomatos',
          'mo': 123656,
          'email': 'tomatos@gmail.com',
          'rating': 4,
        },
      },
      'vadodra': {
        'Peshawri': {
          'name': 'Peshawri',
          'mo': 123756,
          'email': 'peshawri@gmail.com',
          'rating': 4,
        },
        'SheeshMahal': {
          'name': 'Sheesh Mahal',
          'mo': 123856,
          'email': 'sheeshmahal@gmail.com',
          'rating': 3,
        },
        'Zeste': {
          'name': 'Zeste',
          'mo': 123956,
          'email': 'zeste@gmail.com',
          'rating': 3.5,
        },
        'Elysian': {
          'name': 'Elysian',
          'mo': 123056,
          'email': 'elysian@gmail.com',
          'rating': 5,
        },
        'ThatPlace': {
          'name': 'thatPlace',
          'mo': 123156,
          'email': 'thatPlace@gmail.com',
          'rating': 3,
        },
      },
      'kutch': {
        'ParkView': {
          'name': 'ParkView',
          'mo': 123256,
          'email': 'parkview@gmail.com',
          'rating': 4.5,
        },
        'Vekariya': {
          'name': 'vekariya',
          'mo': 123356,
          'email': 'vekariya@gmail.com',
          'rating': 4.5,
        },
        'Umiyaji': {
          'name': 'Umiyaji',
          'mo': 124456,
          'email': 'umiyaji@gmail.com',
          'rating': 3.5,
        },
        'Annapurna': {
          'name': 'Annapurna',
          'mo': 125456,
          'email': 'annapurna@gmail.com',
          'rating': 4,
        },
        'Samsara': {
          'name': 'Samsara',
          'mo': 126456,
          'email': 'samsara@gmail.com',
          'rating': 4,
        },
      },
    },
    'rajsthan': {
      'Jodhpur': {
        'VEDIC': {
          'name': 'VEDIC',
          'mo': 223456,
          'email': 'vedik@gmail.com',
          'rating': 4,
        },
        'Gopal': {
          'name': 'Gopal',
          'mo': 223457,
          'email': 'gopal@gmail.com',
          'rating': 3.5,
        },
        'Kesar': {
          'name': 'Kesar',
          'mo': 223458,
          'email': 'kesar@gmail.com',
          'rating': 3.5,
        },
        'Indique': {
          'name': 'Indique',
          'mo': 223459,
          'email': 'indique@gmail.com',
          'rating': 5,
        },
        'Tamarind': {
          'name': 'Tamarind',
          'mo': 223451,
          'email': 'tamarind@gmail.com',
          'rating': 4,
        },
      },
      'Jaipur': {
        'Skyfall': {
          'name': 'Skyfall',
          'mo': 223452,
          'email': 'skyfall@gmail.com',
          'rating': 5,
        },
        'Giardino': {
          'name': 'Giardino',
          'mo': 223453,
          'email': 'giardino@gmail.com',
          'rating': 4.5,
        },
        'Steam': {
          'name': 'Steam',
          'mo': 223454,
          'email': 'steam@gmail.com',
          'rating': 3.5,
        },
        'Hawk View': {
          'name': 'Hawk View',
          'mo': 223466,
          'email': 'hawkview@gmail.com',
          'rating': 3,
        },
        'Rajput': {
          'name': 'Rajput',
          'mo': 223476,
          'email': 'rajput@gmail.com',
          'rating': 4,
        },
      },
      'Bikaner': {
        'Flames': {
          'name': 'Flames ',
          'mo': 223486,
          'email': 'flames@gmail.com',
          'rating': 4,
        },
        'Aapni Haveli': {
          'name': 'Aapni Haveli',
          'mo': 223496,
          'email': 'aapnihaveli@gmail.com',
          'rating': 3.5,
        },
        'Swadisht': {
          'name': 'Swadisht',
          'mo': 223406,
          'email': 'swadisht@gmail.com',
          'rating': 4.5,
        },
        'SkyBytes': {
          'name': 'SkyBytes',
          'mo': 223556,
          'email': 'skybytes@gmail.com',
          'rating': 5,
        },
        'Sattvic': {
          'name': 'Sattvic',
          'mo': 223656,
          'email': 'sattvic@gmail.com',
          'rating': 4,
        },
      },
      'Udaipur': {
        'Tribute': {
          'name': 'Tribute',
          'mo': 223756,
          'email': 'tribute@gmail.com',
          'rating': 4,
        },
        'Kotra Haveli': {
          'name': 'Kotra Haveli',
          'mo': 223856,
          'email': 'kotrahaveli@gmail.com',
          'rating': 3,
        },
        'Jalsa': {
          'name': 'Jalsa',
          'mo': 223956,
          'email': 'jalsa@gmail.com',
          'rating': 3.5,
        },
        'Natural': {
          'name': 'Natural',
          'mo': 223056,
          'email': 'natural@gmail.com',
          'rating': 5,
        },
        'Jhumar': {
          'name': 'Jhumar',
          'mo': 223156,
          'email': 'jhumar@gmail.com',
          'rating': 3,
        },
      },
      'Ajmer': {
        'Pandit': {
          'name': 'Pandit',
          'mo': 223256,
          'email': 'pandit@gmail.com',
          'rating': 4.5,
        },
        'Tokri': {
          'name': 'Tokri',
          'mo': 223356,
          'email': 'tokri@gmail.com',
          'rating': 4.5,
        },
        'Rasoi': {
          'name': 'Rasoi',
          'mo': 224456,
          'email': 'rasoi@gmail.com',
          'rating': 3.5,
        },
        'Cinnamon': {
          'name': 'Cinnamon',
          'mo': 225456,
          'email': 'cinnamon@gmail.com',
          'rating': 4,
        },
        'Coffoholic': {
          'name': 'Coffoholic',
          'mo': 226456,
          'email': 'coffoholic@gmail.com',
          'rating': 4,
        },
      },
    },
    'maharastra': {
      'Mumbai ': {
        'Ziya': {
          'name': 'Ziya',
          'mo': 323456,
          'email': 'ziya@gmail.com',
          'rating': 4,
        },
        'Yauatcha': {
          'name': 'Yauatcha',
          'mo': 323457,
          'email': 'yauatcha@gmail.com',
          'rating': 3.5,
        },
        'Tanatan': {
          'name': 'Tanatan',
          'mo': 323458,
          'email': 'tanatan@gmail.com',
          'rating': 3.5,
        },
        'Wasabi': {
          'name': 'Wasabi',
          'mo': 323459,
          'email': 'wasabi@gmail.com',
          'rating': 5,
        },
        'Mabruk': {
          'name': 'Mabruk',
          'mo': 323451,
          'email': 'mabruk@gmail.com',
          'rating': 4,
        },
      },
      'Nashik': {
        'Nandinee': {
          'name': 'Nandinee',
          'mo': 323452,
          'email': 'nandinee@gmail.com',
          'rating': 5,
        },
        'Panorama': {
          'name': 'Panorama',
          'mo': 323453,
          'email': 'panorama@gmail.com',
          'rating': 4.5,
        },
        'Radhakrishna': {
          'name': 'Radhakrishna',
          'mo': 323454,
          'email': 'radhakrishna@gmail.com',
          'rating': 3.5,
        },
        'Yahoo': {
          'name': 'Yahoo',
          'mo': 323466,
          'email': 'yahoo@gmail.com',
          'rating': 3,
        },
        'Barbeque Ville': {
          'name': 'Barbeque Ville',
          'mo': 323476,
          'email': 'barbequebille@gmail.com',
          'rating': 4,
        },
      },
      'Pune': {
        'Baan Tao': {
          'name': 'Baan Tao ',
          'mo': 323486,
          'email': 'baanyao@gmail.com',
          'rating': 4,
        },
        'Alto Vino': {
          'name': 'Alto Vino',
          'mo': 323496,
          'email': 'altovino@gmail.com',
          'rating': 3.5,
        },
        'Shabree': {
          'name': 'Shabree',
          'mo': 323406,
          'email': 'shabree@gmail.com',
          'rating': 4.5,
        },
        'Malaka': {
          'name': 'Malaka',
          'mo': 323556,
          'email': 'malaka@gmail.com',
          'rating': 5,
        },
        'Sorriso': {
          'name': 'Sorriso',
          'mo': 323656,
          'email': 'sorriso@gmail.com',
          'rating': 4,
        },
      },
      'Aurangabad': {
        'Naivedya': {
          'name': 'Naivedya',
          'mo': 323756,
          'email': 'naivedya@gmail.com',
          'rating': 4,
        },
        'Kailash': {
          'name': 'Kailash',
          'mo': 323856,
          'email': 'kailash@gmail.com',
          'rating': 3,
        },
        'TeAmo': {
          'name': 'TeAmo',
          'mo': 323956,
          'email': 'teAmo@gmail.com',
          'rating': 3.5,
        },
        'Amigos': {
          'name': 'Amigos',
          'mo': 323056,
          'email': 'amigos@gmail.com',
          'rating': 5,
        },
        'Modak': {
          'name': 'Modak',
          'mo': 323156,
          'email': 'modak@gmail.com',
          'rating': 3,
        },
      },
      'Nagpur': {
        'ZINQ': {
          'name': 'ZINQ',
          'mo': 323256,
          'email': 'zinq@gmail.com',
          'rating': 4.5,
        },
        'Skytouch': {
          'name': 'Skytouch',
          'mo': 323356,
          'email': 'skytouch@gmail.com',
          'rating': 4.5,
        },
        'Haldiram': {
          'name': 'Haldiram',
          'mo': 324456,
          'email': 'haldiram@gmail.com',
          'rating': 3.5,
        },
        'Zuree': {
          'name': 'Zuree',
          'mo': 325456,
          'email': 'zuree@gmail.com',
          'rating': 4,
        },
        'Vishnuji': {
          'name': 'Vishnuji',
          'mo': 326456,
          'email': 'vishnuji@gmail.com',
          'rating': 4,
        },
      },
    },
    'up': {
      'Kanpur': {
        'Pind Balluchi': {
          'name': 'Pind Balluchi',
          'mo': 423456,
          'email': 'pindballuchi@gmail.com',
          'rating': 4,
        },
        'Dhuaan': {
          'name': 'Dhuaan',
          'mo': 423457,
          'email': 'dhuaan@gmail.com',
          'rating': 3.5,
        },
        'Kwality': {
          'name': 'Kwality',
          'mo': 423458,
          'email': 'kwality@gmail.com',
          'rating': 3.5,
        },
        'Barracks': {
          'name': 'Barracks',
          'mo': 423459,
          'email': 'barracks@gmail.com',
          'rating': 5,
        },
        'Anaicha': {
          'name': 'Anaicha',
          'mo': 423451,
          'email': 'anaicha@gmail.com',
          'rating': 4,
        },
      },
      'Lucknow': {
        'LukJin': {
          'name': 'LukJin',
          'mo': 423452,
          'email': 'lukjin@gmail.com',
          'rating': 5,
        },
        'ROCCA': {
          'name': 'ROCCA',
          'mo': 423453,
          'email': 'rocca@gmail.com',
          'rating': 4.5,
        },
        'Falak Numa': {
          'name': 'Falak Numa',
          'mo': 423454,
          'email': 'falaknuma@gmail.com',
          'rating': 3.5,
        },
        'SAQI': {
          'name': 'SAQI',
          'mo': 423466,
          'email': 'saqi@gmail.com',
          'rating': 3,
        },
        'Oudhyana': {
          'name': 'Oudhyana',
          'mo': 423476,
          'email': 'qudhyana@gmail.com',
          'rating': 4,
        },
      },
      'Ghaziabad': {
        'ROOFTOP': {
          'name': 'ROOFTOP ',
          'mo': 423486,
          'email': 'rooftop@gmail.com',
          'rating': 4,
        },
        'Clubate': {
          'name': 'Clubate',
          'mo': 423496,
          'email': 'clubate@gmail.com',
          'rating': 3.5,
        },
        'Tangerine': {
          'name': 'Tangerine',
          'mo': 423406,
          'email': 'tangerine@gmail.com',
          'rating': 4.5,
        },
        'Madan': {
          'name': 'Madan',
          'mo': 423556,
          'email': 'madan@gmail.com',
          'rating': 5,
        },
        'Citrus Cafe': {
          'name': 'Citrus Cafe',
          'mo': 423656,
          'email': 'citruscafe@gmail.com',
          'rating': 4,
        },
      },
      'Agra': {
        'Yash Cafe': {
          'name': 'Yash Cafe',
          'mo': 423756,
          'email': 'yashcafe@gmail.com',
          'rating': 4,
        },
        'Joney' 's Place': {
          'name': 'Joney' 's Place',
          'mo': 123856,
          'email': 'joneysplace@gmail.com',
          'rating': 3,
        },
        'Sankara': {
          'name': 'Sankara',
          'mo': 423956,
          'email': 'sankara@gmail.com',
          'rating': 3.5,
        },
        'Taj terrace': {
          'name': 'Taj terrace',
          'mo': 423056,
          'email': 'tajterrace@gmail.com',
          'rating': 5,
        },
        'Pankhuri': {
          'name': 'Pankhuri',
          'mo': 423156,
          'email': 'pankhuri@gmail.com',
          'rating': 3,
        },
      },
      'Meerut': {
        'Woodhouse': {
          'name': 'Woodhouse',
          'mo': 423256,
          'email': 'woodhouse@gmail.com',
          'rating': 4.5,
        },
        'Outer Limit': {
          'name': 'Outer Limit',
          'mo': 423356,
          'email': 'quterlimit@gmail.com',
          'rating': 4.5,
        },
        'Vandini': {
          'name': 'Vandini',
          'mo': 424456,
          'email': 'vandini@gmail.com',
          'rating': 3.5,
        },
        'Hangries': {
          'name': 'Hangries',
          'mo': 425456,
          'email': 'hangries@gmail.com',
          'rating': 4,
        },
        'Spice Affair': {
          'name': 'Spice Affair',
          'mo': 426456,
          'email': 'spiceaffair@gmail.com',
          'rating': 4,
        },
      },
    },
    'mp': {
      'Indore': {
        'Mediterra': {
          'name': 'Mediterra',
          'mo': 523456,
          'email': 'mediterra@gmail.com',
          'rating': 4,
        },
        'Nafees': {
          'name': 'Nafees',
          'mo': 523457,
          'email': 'nafees@gmail.com',
          'rating': 3.5,
        },
        'Praangan': {
          'name': 'Praangan',
          'mo': 523458,
          'email': 'praangan@gmail.com',
          'rating': 3.5,
        },
        'Capers': {
          'name': 'Capers',
          'mo': 523459,
          'email': 'capers@gmail.com',
          'rating': 5,
        },
        'Chopstick': {
          'name': 'Chopstick',
          'mo': 523451,
          'email': 'chopstick@gmail.com',
          'rating': 4,
        },
      },
      'Bhopal': {
        'Kebabsville': {
          'name': 'Kebabsville',
          'mo': 523452,
          'email': 'kebabsville@gmail.com',
          'rating': 5,
        },
        'Shikha': {
          'name': 'Shikha',
          'mo': 523453,
          'email': 'shikha@gmail.com',
          'rating': 4.5,
        },
        'Manohar': {
          'name': 'Manohar',
          'mo': 523454,
          'email': 'manohar@gmail.com',
          'rating': 3.5,
        },
        'Shahnama': {
          'name': 'Shahnama',
          'mo': 523466,
          'email': 'shahnama@gmail.com',
          'rating': 3,
        },
        'Cowboy': {
          'name': 'Cowboy',
          'mo': 523476,
          'email': 'cowboy@gmail.com',
          'rating': 4,
        },
      },
      'Jabalpur': {
        'Panchvati': {
          'name': 'Panchvati ',
          'mo': 523486,
          'email': 'panchvati@gmail.com',
          'rating': 4,
        },
        'Kamling': {
          'name': 'Kamling',
          'mo': 523496,
          'email': 'kamling@gmail.com',
          'rating': 3.5,
        },
        'Asanzo': {
          'name': 'Asanzo',
          'mo': 523406,
          'email': 'asanzo@gmail.com',
          'rating': 4.5,
        },
        'Peppers': {
          'name': 'Peppers',
          'mo': 523556,
          'email': 'peppers@gmail.com',
          'rating': 5,
        },
        'Maurya': {
          'name': 'Maurya',
          'mo': 523656,
          'email': 'maurya@gmail.com',
          'rating': 4,
        },
      },
      'Gwalior': {
        'Raj Bhoj': {
          'name': 'Raj Bhoj',
          'mo': 523756,
          'email': 'rajbhoj@gmail.com',
          'rating': 4,
        },
        'Victorian Vantage': {
          'name': 'Victorian Vantage',
          'mo': 523856,
          'email': 'victorianvantage@gmail.com',
          'rating': 3,
        },
        'Alfanzo': {
          'name': 'Alfanzo',
          'mo': 523956,
          'email': 'alfanzo@gmail.com',
          'rating': 3.5,
        },
        'BansiWala': {
          'name': 'BansiWala',
          'mo': 523056,
          'email': 'bansiWala@gmail.com',
          'rating': 5,
        },
        'Naivedyam': {
          'name': 'Naivedyam',
          'mo': 523156,
          'email': 'naivedyam@gmail.com',
          'rating': 3,
        },
      },
      'Ujjain': {
        'Swaruchi': {
          'name': 'Swaruchi',
          'mo': 523256,
          'email': 'swaruchi@gmail.com',
          'rating': 4.5,
        },
        'Bholaguru': {
          'name': 'Bholaguru',
          'mo': 523356,
          'email': 'bholaguru@gmail.com',
          'rating': 4.5,
        },
        'Empire': {
          'name': 'Empire',
          'mo': 524456,
          'email': 'empire@gmail.com',
          'rating': 3.5,
        },
        'Shree Ganga': {
          'name': 'Shree Ganga',
          'mo': 525456,
          'email': 'shreeganga@gmail.com',
          'rating': 4,
        },
        'AYUSHMAN': {
          'name': 'AYUSHMAN',
          'mo': 526456,
          'email': 'ayushman@gmail.com',
          'rating': 4,
        },
      },
    },
  };
}
